/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import config.Koneksi;
import form.ArsipView;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class FrormHasil extends javax.swing.JFrame {
private final Connection conn;
    /**
     * Creates new form FrormHasil
     */
    public FrormHasil() {
        initComponents();
        conn = Koneksi.getConnection();
        getData();
    }

    private void getData() {
        DefaultTableModel model = (DefaultTableModel) table_Hasil.getModel();
        model.setRowCount(0); // Mengosongkan tabel sebelum menambahkan data baru
        
        try {
            String sql = "SELECT * FROM table_hasil";
            PreparedStatement ps = conn.prepareStatement(sql); 
            ResultSet rs = ps.executeQuery();
            
            while(rs.next()) {
                int kd_hasil = rs.getInt("kd_hasil");
                int kd_arsip = rs.getInt("kd_arsip"); // Mengambil nilai dari kolom kd_arsip
                String no_surat = rs.getString("no_surat"); // Mengambil nilai dari kolom arsip
                String kd_progres = rs.getString("no_surat"); // Mengambil nilai dari kolom arsip
                String tgl_jawab = rs.getString("tgl_jawab"); // Mengambil nilai dari kolom arsip
                String hasil = rs.getString("hasil"); // Mengambil nilai dari kolom arsip
                String kd_penyakit = rs.getString("kd_penyakit"); // Mengambil nilai dari kolom arsip
                String jml_diagnosa = rs.getString("jml_diagnosa"); // Mengambil nilai dari kolom arsip
                    
                Object[] rowData = {kd_hasil, kd_arsip, no_surat, kd_progres, tgl_jawab, hasil, kd_penyakit, jml_diagnosa}; // Membuat array objek untuk baris data
                model.addRow(rowData); // Menambahkan baris data ke dalam tabel
            
            }
            rs.close();
            ps.close();
        } catch (Exception e) {
            Logger.getLogger(ArsipView.class.getName()).log(Level.SEVERE, null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        t_KdHasil = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t_Arsip = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t_Surat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        t_Progres = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tsa = new javax.swing.JLabel();
        t_Tanggal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        t_Penyakit = new javax.swing.JTextField();
        sa = new javax.swing.JLabel();
        t_Diagnosa = new javax.swing.JTextField();
        btn_Simpan = new javax.swing.JButton();
        btn_Ubah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Hasil = new javax.swing.JTable();
        t_Hasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("kode_hasil");

        jLabel2.setText("kode_Arsip");

        jLabel3.setText("no_surat");

        jLabel4.setText("kode_Progres");

        tsa.setText("Tanggal_jawab");

        jLabel6.setText("Hasil");

        jLabel7.setText("Kode_penyakit");

        sa.setText("Jumlah_diagnosa");

        btn_Simpan.setText("SIMPAN");
        btn_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SimpanActionPerformed(evt);
            }
        });

        btn_Ubah.setText("UBAH");
        btn_Ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UbahActionPerformed(evt);
            }
        });

        table_Hasil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        table_Hasil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_HasilMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_Hasil);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addGap(116, 116, 116))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(t_Arsip, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(t_KdHasil, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(t_Progres, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                        .addComponent(t_Surat, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t_Penyakit)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(sa)
                                            .addComponent(t_Diagnosa, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 37, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t_Tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tsa))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addGap(45, 45, 45)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_Simpan)
                            .addComponent(btn_Ubah))
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t_Hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(tsa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_KdHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_Tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_Simpan)
                        .addComponent(jLabel6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(t_Arsip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btn_Ubah))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(t_Hasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_Surat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_Penyakit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sa))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_Progres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_Diagnosa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SimpanActionPerformed
        // TODO add your handling code here:
        String kd_hasil = t_KdHasil.getText();
        String kd_arsip = t_Arsip.getText();
        String no_surat = t_Surat.getText();
        String kd_progres = t_Progres.getText();
        String tgl_jawab = t_Tanggal.getText();
        String hasil = t_Hasil.getText();
        String kd_penyakit = t_Penyakit.getText();
        String jml_diagnosa = t_Diagnosa.getText();
        
        if(kd_hasil.isEmpty() || kd_arsip.isEmpty() || no_surat.isEmpty() || kd_progres.isEmpty() || tgl_jawab.isEmpty() || hasil.isEmpty() || kd_penyakit.isEmpty() || jml_diagnosa.isEmpty()) {
        JOptionPane.showMessageDialog(this, "semua kolum haris di sisi", "validasi", JOptionPane.ERROR_MESSAGE);
        return;
        }
        
        try {
            String sql = "insert into table_hasil (kd_hasil,kd_arsip,no_surat,kd_progres,tgl_jawab,hasil,kd_penyakit,jml_diagnosa) VALUES (?,?,?,?,?,?,?,?)";
            try (PreparedStatement st = conn.prepareStatement(sql)) {
                st.setString(1, kd_hasil);
                st.setString(2, kd_arsip);
                st.setString(3, no_surat);
                st.setString(4, kd_progres);
                st.setString(5, tgl_jawab);
                st.setString(6, hasil);
                st.setString(7, kd_penyakit);
                st.setString(8, jml_diagnosa);
                
                int rowInserted = st.executeUpdate();
                if(rowInserted >0) {
                    JOptionPane.showMessageDialog(this, "data berhasil ditambahkan");
                    resetForm();
                    getData();
                }
            }
        } catch (Exception e) {
            Logger.getLogger(ArsipView.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btn_SimpanActionPerformed

    private void btn_UbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UbahActionPerformed
        // TODO add your handling code here:
     int selectedRow = table_Hasil.getSelectedRow();
        
     if(selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "pilih baris yang akan dipergarui");
        return;
        }    
    String kd_hasil = table_Hasil.getValueAt(selectedRow, 0).toString();
    String kd_arsip = t_Arsip.getText();
    String no_surat = t_Surat.getText();
    String kd_progres = t_Progres.getText();
    String tgl_jawab = t_Tanggal.getText();
    String hasil = t_Hasil.getText();
    String kd_penyakit = t_Penyakit.getText();
    String jml_diagnosa = t_Diagnosa.getText();
    
    if(kd_hasil.isEmpty() || kd_arsip.isEmpty() || no_surat.isEmpty() || kd_progres.isEmpty() || tgl_jawab.isEmpty() || hasil.isEmpty() || kd_penyakit.isEmpty() || jml_diagnosa.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Semua kolom harus diisi", "Validasi", JOptionPane.ERROR_MESSAGE);
        return;
        }
    
        try {
            String sql = "UPDATE INTO table_hasil SET kd_arsip=?, no_surat=?, kd_progres=?, tgl_jawab=?, hasil=?, kd_penyakit=?, jml_diagnosa=? WHERE kd_hasil=?";
             PreparedStatement st = conn.prepareStatement(sql);
            st.setString(1, kd_arsip);
            st.setString(2, no_surat);
            st.setString(3, kd_progres);
            st.setString(4, tgl_jawab);
            st.setString(5, hasil);
            st.setString(6, kd_penyakit);
            st.setString(7, jml_diagnosa);
            st.setString(8, kd_hasil);
            
            int rowUpdate = st.executeUpdate();
            if(rowUpdate > 0) {
                JOptionPane.showMessageDialog(this, "data berhasil diubah");
            resetForm();
            getData();
            }
            st.close();
        } catch (HeadlessException | SQLException e) {
            Logger.getLogger(ArsipView.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btn_UbahActionPerformed

    private void table_HasilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_HasilMouseClicked
        // TODO add your handling code here:
        int selectRow = table_Hasil.getSelectedRow();
        if(selectRow != -1) {
        int selectedRow = 0;
        String kd_hasil = table_Hasil.getValueAt(selectedRow, 0).toString();
        String kd_arsip = table_Hasil.getValueAt(selectedRow, 1).toString();
        String no_surat = table_Hasil.getValueAt(selectedRow, 2).toString();
        String kd_progres = table_Hasil.getValueAt(selectedRow, 3).toString();
        String tgl_jawab = table_Hasil.getValueAt(selectedRow, 4).toString();
        String hasil = table_Hasil.getValueAt(selectedRow, 5).toString();
        String kd_penyakit = table_Hasil.getValueAt(selectedRow, 6).toString();
        String jml_diagnosa = table_Hasil.getValueAt(selectedRow, 7).toString();
        
        t_KdHasil.setText(kd_hasil);
        t_Arsip.setText(kd_arsip);
        t_Surat.setText(no_surat);
        t_Progres.setText(kd_progres);
        t_Tanggal.setText(tgl_jawab);
        t_Hasil.setText(hasil);
        t_Penyakit.setText(kd_penyakit);
        t_Diagnosa.setText(jml_diagnosa);
    }//GEN-LAST:event_table_HasilMouseClicked


        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrormHasil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Simpan;
    private javax.swing.JButton btn_Ubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel sa;
    private javax.swing.JTextField t_Arsip;
    private javax.swing.JTextField t_Diagnosa;
    private javax.swing.JTextField t_Hasil;
    private javax.swing.JTextField t_KdHasil;
    private javax.swing.JTextField t_Penyakit;
    private javax.swing.JTextField t_Progres;
    private javax.swing.JTextField t_Surat;
    private javax.swing.JTextField t_Tanggal;
    private javax.swing.JTable table_Hasil;
    private javax.swing.JLabel tsa;
    // End of variables declaration//GEN-END:variables

    private void resetForm() {
        t_KdHasil.setText("");
        t_Arsip.setText("");
        t_Surat.setText("");
        t_Progres.setText("");
        t_Tanggal.setText("");
        t_Hasil.setText("");
        t_Penyakit.setText("");
        t_Diagnosa.setText("");
    }

    
}
