/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import config.Koneksi;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author User
 */
public class HewanView extends javax.swing.JFrame {
private final Connection conn;
    /**
     * Creates new form HewanView
     */
    public HewanView() {
        initComponents();
        conn =Koneksi.getConnection();
        getData();
    }

    private void getData() {
        DefaultTableModel model = (DefaultTableModel) tbl_Hewan.getModel();
        model.setRowCount(0); // Mengosongkan tabel sebelum menambahkan data baru
        
        try {
            String sql = "SELECT * FROM table_hewan";
            PreparedStatement ps = conn.prepareStatement(sql); 
            ResultSet rs = ps.executeQuery();
                
            while (rs.next()) {
                int kd_hewan = rs.getInt("kd_hewan"); // Mengambil nilai dari kolom kd_arsip
                String hewan = rs.getString("hewan"); // Mengambil nilai dari kolom arsip
                    
                Object[] rowData = {kd_hewan, hewan}; // Membuat array objek untuk baris data
                model.addRow(rowData); // Menambahkan baris data ke dalam tabel
                
            }
            rs.close();
            ps.close();
        } catch (SQLException e) {
            Logger.getLogger(ArsipView.class.getName()).log(Level.SEVERE, null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_Simpan = new javax.swing.JButton();
        btn_Ubah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        t_KodeHewa = new javax.swing.JTextField();
        t_Hewan = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Hewan = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Kode_hewa");

        jLabel2.setText("Hewa");

        btn_Simpan.setText("SIMPAN");
        btn_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SimpanActionPerformed(evt);
            }
        });

        btn_Ubah.setText("UBAH");
        btn_Ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UbahActionPerformed(evt);
            }
        });

        btn_hapus.setText("HAPUS");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        t_KodeHewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_KodeHewaActionPerformed(evt);
            }
        });

        t_Hewan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_HewanActionPerformed(evt);
            }
        });

        tbl_Hewan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_Hewan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_HewanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_Hewan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_hapus))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(54, 54, 54)
                                        .addComponent(t_KodeHewa))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                        .addComponent(t_Hewan, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_Ubah, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_Simpan, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Simpan)
                    .addComponent(t_KodeHewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btn_Ubah)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(t_Hewan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)))
                .addComponent(btn_hapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_KodeHewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_KodeHewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_KodeHewaActionPerformed

    private void t_HewanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_HewanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_HewanActionPerformed

    private void btn_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SimpanActionPerformed
        // TODO add your handling code here:
        String kd_hewan = t_KodeHewa.getText();
        String hewan = t_Hewan.getText();
        
        if(kd_hewan.isEmpty() || hewan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "semua kolum haris di sisi", "validasi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            String sql = "insert into table_hewan (kd_hewan,hewan) VALUES (?,?)";
            try (PreparedStatement st = conn.prepareStatement(sql)) {
                st.setString(1, kd_hewan);
                st.setString(2, hewan);
                
                int rowInserted = st.executeUpdate();
                if(rowInserted >0) {
                    JOptionPane.showMessageDialog(this, "data berhasil ditambahkan");
                    resetForm();
                    getData();
                }
            }
        } catch (SQLException e) {
            Logger.getLogger(ArsipView.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btn_SimpanActionPerformed

    private void btn_UbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UbahActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbl_Hewan.getSelectedRow();
        if(selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "pilih baris yang akan dipergarui");
        return;
        }
        
        String kd_hewan =tbl_Hewan.getValueAt(selectedRow, 0).toString();
        String hewan = t_Hewan.getText();
        
        if(hewan.isEmpty()) {
        JOptionPane.showMessageDialog(this, "semua kolom harus diisi", "validasi", JOptionPane.ERROR_MESSAGE);
        return;
            }
        
        try {
        String sql = "UPDATE table_hewan SET hewan=? WHERE kd_hewan=?";
        PreparedStatement st = conn.prepareStatement(sql);
            st.setString(1, hewan);
            st.setString(2, kd_hewan);
            
            int rowUpdate = st.executeUpdate();
            if(rowUpdate > 0) {
                JOptionPane.showMessageDialog(this, "data berhasil diubah");
                resetForm();
                getData();
            }
            
            st.close();
        } catch (HeadlessException | SQLException e) {
            Logger.getLogger(ArsipView.class.getName()).log(Level.SEVERE, null, e);
        } 
    }//GEN-LAST:event_btn_UbahActionPerformed

    private void tbl_HewanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_HewanMouseClicked
        // TODO add your handling code here:
        int selectRow = tbl_Hewan.getSelectedRow();
        if(selectRow != -1) {
        int selectedRow = 0;
        String kd_hewan = tbl_Hewan.getValueAt(selectedRow, 0).toString();
        String hewan = tbl_Hewan.getValueAt(selectedRow, 1).toString();
        
        t_KodeHewa.setText(kd_hewan);
        t_Hewan.setText(hewan);
        }
    }//GEN-LAST:event_tbl_HewanMouseClicked

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbl_Hewan.getSelectedRow();
        if(selectedRow == -1){
            JOptionPane.showMessageDialog(this, "");
            return;
        }
        int confirm =JOptionPane.showConfirmDialog(this, "apakah anda yakin ingin menghapus data ini?","Konfirmasi",JOptionPane.YES_OPTION);
        if(confirm== JOptionPane.YES_OPTION) {
            String kd_hewan = tbl_Hewan.getValueAt(selectedRow, 0).toString();
            
            try {
               String sql = "DELETE FROM table_hewan WHERE kd_hewan=?";
               PreparedStatement st = conn.prepareStatement(sql);  
               st.setString(1, kd_hewan);
               
               int rowDelete = st.executeUpdate();
               if(rowDelete > 0) {
                   JOptionPane.showMessageDialog(this, "data Berhasil dihapus");
                   resetForm();
                   getData();
               }
               st.close();
            } catch (HeadlessException | SQLException e) {
            Logger.getLogger(ArsipView.class.getName()).log(Level.SEVERE, null, e);
            }
    }//GEN-LAST:event_btn_hapusActionPerformed

    //</editor-fold>
    
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new HewanView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Simpan;
    private javax.swing.JButton btn_Ubah;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField t_Hewan;
    private javax.swing.JTextField t_KodeHewa;
    private javax.swing.JTable tbl_Hewan;
    // End of variables declaration//GEN-END:variables

    private void resetForm() {
        t_KodeHewa.setText("");
        t_Hewan.setText("");
    }


}
