
package form;
/**
 *
 * @author User
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemKeluar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemArsip = new javax.swing.JMenuItem();
        menuItemHasil = new javax.swing.JMenuItem();
        menuItemProgres = new javax.swing.JMenuItem();
        menuItemHewan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        menuItemKeluar.setText("Keluar");
        menuItemKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemKeluarActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemKeluar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Data");

        menuItemArsip.setText("Arisp");
        menuItemArsip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemArsipActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemArsip);

        menuItemHasil.setText("Hasil");
        menuItemHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemHasilActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemHasil);

        menuItemProgres.setText("Progres");
        menuItemProgres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProgresActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemProgres);

        menuItemHewan.setText("Hewan");
        menuItemHewan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemHewanActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemHewan);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_menuItemKeluarActionPerformed

    private void menuItemArsipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemArsipActionPerformed
        // TODO add your handling code here:
        new ArsipView().setVisible(true);
    }//GEN-LAST:event_menuItemArsipActionPerformed

    private void menuItemHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemHasilActionPerformed
        // TODO add your handling code here:
        new FrormHasil().setVisible(true);
    }//GEN-LAST:event_menuItemHasilActionPerformed

    private void menuItemProgresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProgresActionPerformed
        // TODO add your handling code here:
        new ProgresView().setVisible(true);
    }//GEN-LAST:event_menuItemProgresActionPerformed

    private void menuItemHewanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemHewanActionPerformed
        // TODO add your handling code here:
        new HewanView().setVisible(true);
    }//GEN-LAST:event_menuItemHewanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Home().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuItemArsip;
    private javax.swing.JMenuItem menuItemHasil;
    private javax.swing.JMenuItem menuItemHewan;
    private javax.swing.JMenuItem menuItemKeluar;
    private javax.swing.JMenuItem menuItemProgres;
    // End of variables declaration//GEN-END:variables

}
